### ISSUE TITLE
Cannot attach XDP to interfaceX

### ISSUE THREAD

**Issue by aaronchn** [ahsifer/goxdp#1]
Hi Safar

If anyone is not familiar with ebpf and would like to quickly try out the ebpf-based package handling features, your code would be very helpful. Thanks for your contribution!

An error is encountered when trying to execute the following command execution：
```
# ./goxdp client --action=load --interfaces=eno2 --mode=skb
Cannot attach XDP to eno2 XDP might be already loaded to the interface  -> create link: invalid argument
# ./goxdp client --action=load --interfaces=eno2 --mode=skb --dstIP=127.0.0.1 --dstPort=8090
Cannot attach XDP to eno2 XDP might be already loaded to the interface  -> create link: invalid argument
```
The server's log
```
ERROR   handlers.go:77: Cannot attach XDP to eno2 XDP might be already loaded to the interface  -> create link: invalid argument
"POST http://127.0.0.1:8090/load HTTP/1.1" from 127.0.0.1:49347 - 400 138B in 1.446057ms
```
I tried looking at the interface using commands like ip link list dev eno2 and did not find anything like xdp.
Also, the environment I'm trying is redhat 7.6 with kernel 4.19.0.

It's confusing to determine if it's a problem with the environment's support for goxdp or a other error.
Please know.

**Comment by ahsifer** [comment]
Hi @aaronchn,
Thank you for your feedback, I think the issue is related to the environment because Redhat 7.6 uses XDP only for tracing purposes as explained [here](https://www.redhat.com/en/blog/introduction-ebpf-red-hat-enterprise-linux-7#:~:text=eBPF%20in%20Red%20Hat%20Enterprise%20Linux%207.6%20is%20enabled%20only%20for%20tracing%20purposes%2C%20which%20allows%20attaching%20eBPF%20programs%20to%20probes%2C%20tracepoints%20and%20perf%20events.%20Other%20use%20cases%20such%20as%20eBPF%20socket%20filters%20or%20eXpress%20DataPath%20(XDP)%20are%20not%20enabled%20at%20this%20stage.). Also, I am unsure even if it is supported in version 7.
